### ISSUE TITLE
Too large and inconvenient area of soil change under the pillar

### ISSUE THREAD

**Issue by vitalii2011** [Achimobil/FS22_BigDisplay#13]
![0010](https://github.com/Achimobil/FS22_BigDisplay/assets/41552153/27359e07-11c5-4fdb-a850-c8ec5a9a5507)

**Comment by Achimobil** [comment]
The leveling Area is 1x1m exact around the model. Seems the LS has a problem with such small areas.
But I will have a look in some placable light mods if I can see something I can make better for the next big update

**Comment by vitalii2011** [comment]
Such vanilla objects do not have such a problem: 
![fsScreen_2023_05_31_14_31_10](https://github.com/Achimobil/FS22_BigDisplay/assets/41552153/d90061ad-2df6-4014-b37f-71da8596a6fc)
![fsScreen_2023_05_31_14_34_03](https://github.com/Achimobil/FS22_BigDisplay/assets/41552153/94915206-304f-4a9e-819b-80b5a5530d5e)
![fsScreen_2023_05_31_14_34_18](https://github.com/Achimobil/FS22_BigDisplay/assets/41552153/dd14bd6f-14e5-4958-8652-143f2d9f112d) 
For comparison:
![0012](https://github.com/Achimobil/FS22_BigDisplay/assets/41552153/6b249e0e-b8dd-4a3a-88bb-7f2ab1c11960)


From the mod https://www.farming-simulator.com/mod.php?mod_id=225963
![0011](https://github.com/Achimobil/FS22_BigDisplay/assets/41552153/b289748c-cb80-4d92-a740-6426fddeba1a)

**Comment by Achimobil** [comment]
Thanks, so I will take a look what they have done there different.
