### ISSUE TITLE
Text Colours

### ISSUE THREAD

**Issue by Harag9** [Achimobil/FS22_BigDisplay#17]
First, Excellent Mod, many thanks for this. Really missed this mod from FS19.

On one of your screen shots it shows coloured text but all the others show green text - How do I get it to display coloured text? Is there a setting to specify which fill type is what colour?

**Comment by Achimobil** [comment]
It has different colors at productions depend on if it is input, output or both. That is automatic

**Comment by Harag9** [comment]
Ahh Excellent. Many thanks for that. Wasn't aware it could go on production buildings as well.
