### ISSUE TITLE
LUA-Call-Stacks

### ISSUE THREAD

**Issue by MeRida2104** [Achimobil/FS22_BigDisplay#22]
Hallo Achim,

im Log unseres Dedicated Servers sind LUA-Call-Stacks aufgrund von BigDisplay aufgetreten. Könntest du bitte einen Blick darauf werfen?

```
2024-01-12 12:09 Warning (script): Unknown entity id 500426 for 'object' in method 'getWorldTranslation'.
2024-01-12 12:09 LUA call stack:
  =C:/Users/alex/OneDrive/Dokumente/My Games/FarmingSimulator2022/mods/Multiplayer Farming Crew/FS22_BigDisplay/scripts/bigDisplaySpecialization.lua (324) : getWorldTranslation
  =C:/Users/alex/OneDrive/Dokumente/My Games/FarmingSimulator2022/mods/Multiplayer Farming Crew/FS22_BigDisplay/scripts/bigDisplaySpecialization.lua (225) : getDistance
  =C:/Users/alex/OneDrive/Dokumente/My Games/FarmingSimulator2022/mods/Multiplayer Farming Crew/FS22_BigDisplay/scripts/bigDisplaySpecialization.lua (313) : reconnectToStorage
  dataS/scripts/network/Object.lua (47)
  dataS/scripts/objects/LoadingStation.lua (92) : delete
  dataS/scripts/objects/ProductionPoint.lua (469) : delete
  dataS/scripts/utils/Utils.lua (472) : oldFunc
  dataS/scripts/placeables/specializations/PlaceableProductionPoint.lua (100) : delete
  dataS/scripts/specialization/SpecializationUtil.lua (23)
  dataS/scripts/placeables/Placeable.lua (591) : raiseEvent
  dataS/scripts/network/NetworkNode.lua (87) : delete
  dataS/scripts/network/Client.lua (53) : delete
  dataS/scripts/BaseMission.lua (223) : delete
  dataS/scripts/FSBaseMission.lua (338) : delete
  dataS/scripts/utils/Utils.lua (460) : oldFunc
  dataS/scripts/utils/Utils.lua (460) : oldFunc
  dataS/scripts/utils/Utils.lua (460) : oldFunc
  dataS/scripts/utils/Utils.lua (460) : oldFunc
  dataS/scripts/utils/Utils.lua (460) : oldFunc
  dataS/scripts/utils/Utils.lua (460) : oldFunc
  dataS/scripts/utils/Utils.lua (460) : oldFunc
  dataS/scripts/utils/Utils.lua (460) : oldFunc
  dataS/scripts/utils/Utils.lua (460) : oldFunc
  dataS/scripts/utils/Utils.lua (472) : oldFunc
  dataS/scripts/utils/Utils.lua (460) : oldFunc
  dataS/scripts/missions/mission00.lua (84) : delete
  =C:/Users/alex/OneDrive/Dokumente/My Games/FarmingSimulator2022/mods/Multiplayer Farming Crew/FS22_BetterContracts/scripts/RoyalMod.lua (387) : Mission00delete
  dataS/scripts/menu.lua (141) : delete
  dataS/scripts/gui/InGameMenu.lua (501) : OnInGameMenuMenu
  dataS/scripts/gui/InGameMenu.lua (839) : leaveCurrentGame
  dataS/scripts/gui/dialogs/YesNoDialog.lua (68) : callbackFunc
  dataS/scripts/gui/dialogs/YesNoDialog.lua (100) : sendCallback
  dataS/scripts/gui/elements/ButtonElement.lua (762) : raiseCallback
  dataS/scripts/gui/elements/ButtonElement.lua (475) : sendAction
  dataS/scripts/gui/elements/GuiElement.lua (612) : mouseEvent
  dataS/scripts/gui/elements/GuiElement.lua (612) : mouseEvent
  dataS/scripts/gui/elements/GuiElement.lua (612) : mouseEvent
  dataS/scripts/gui/base/Gui.lua (666) : mouseEvent
  dataS/scripts/events.lua (26) : mouseEvent
```

Beste Grüße
MeRida
[log.txt](https://github.com/Achimobil/FS22_BigDisplay/files/13964423/log.txt)

**Comment by Achimobil** [comment]
Bitte erst mal alle Mods mit Errors und warnings entfernen. Dann auch die raus nehmen die ich im Support ausschließe siehe https://discord.com/channels/919854837972205579/1188252203400573039 und dann nachstellen.

Wenn der Fehler dann nachstellbar ist, dann gern hier innerhalb der nächsten 2 Wochen eine neue Log von einem Spiel rein packen und nicht eine Log mit mehreren Spielstarts. Und dann auch beschreiben wie ich den Fehler nachstellen kann.

Generell sagt der Fehler, dass etwas da sein müsste, was aber nicht da ist und somit werden ich nichts machen solange noch Mods mit generellen Fehlern da sind oder die Verschlüsselt sind. Oder einfach eine Beschreibung wie ich das auf der Standard Map nur mit meinem Mod nachstellen kann, dann schau ich mir das auch gern genauer an.

**Comment by MeRida2104** [comment]
Ich habe nochmals versucht es nachzustellen, aber ohne Ergebnis. Wenn ich es nachstellen kann, öffne ich ein neues issue.

**Comment by Achimobil** [comment]
Super, ich nutze den Better Contract in der neusten Version auch und ich hab jetzt extra auch mal ein Display hingestellt in unserem MP Projekt, aber bisher ohne fehler.

**Comment by Achimobil** [comment]
Fehler konnte jetzt auch ohne Better Contracts oder verschlüsselte Mods im NF Marsch Team nachgestellt werden.
Die Analyze der logs hat ergeben:
- Es passiert wenn das Spiel beendet wird (zurück zum Menü)
- Es wird dann alles gelöscht und die loadingstation wird gelöscht vor dem Display (nur dann tritt der Fehler auf)
- Display versucht sich neu zu verbinden mit loadingstations während gerade gelöscht werden, deshalb weg während der prüfung

Idee:
Aufgerufen wird: g_currentMission.delete() 
Darin wird self.isExitingGame = true gesetzt.

Man könnte also im onStationDeleted des displays ein if (g_currentMission.isExitingGame) abfragen

**Comment by Achimobil** [comment]
Fehler müsste mit der Version 1.0.0.1 behoben sein, gleich zu finden hier als beta

**Comment by MeRida2104** [comment]
Hallo Achim,

hattest du das Update auf einem Dedicated Server getestet? Ich habe es heute auf unseren Server gepusht, allerdings kann man dann nicht mehr connecten.

Das Server-Log ist sauber, in meinem lokalen Log wirft er folgendes:

```
2024-02-02 10:27 Error: Running LUA method 'packetReceived'.
C:/Users/alex/OneDrive/Dokumente/My Games/FarmingSimulator2022/mods/Multiplayer Farming Crew/FS22_BigDisplay/scripts/bigDisplaySpecialization.lua:29: attempt to concatenate global 'g_currentModName' (a nil value)
2024-02-02 10:27 Error: Running LUA method 'packetReceived'.
```


Hier das gesamte Log: 
[log.txt](https://github.com/Achimobil/FS22_BigDisplay/files/14138093/log.txt)

**Comment by Achimobil** [comment]
Da ich den Fehler in meinen Savegames nicht bekomme, kann so was passieren.
Ich hoffe ich hab es mit [1.0.0.2](https://github.com/Achimobil/FS22_BigDisplay/releases/tag/1.0.0.2) behoben.

**Comment by MeRida2104** [comment]
Im Singleplayer bekam ich den Fehler auch nicht. Ich teste es mal auf unserem Dedi Server. Danke für die Anpassung!

**Comment by MeRida2104** [comment]
Läuft, danke für die Mühen und Unterstützung!!

**Comment by Achimobil** [comment]
Tritt leider immer noch auf, muss ich noch mal analysieren.

[log.txt](https://github.com/Achimobil/FS22_BigDisplay/files/14205496/log.txt)

**Comment by Achimobil** [comment]
Noch mal genauer untersucht und mit 1.0.0.6 sollte das jetzt endlich behoben sein
