### ISSUE TITLE
Selbst beschriftbare Anzeige-Displays

### ISSUE THREAD

**Issue by Kitekater** [Achimobil/FS22_BigDisplay#25]
Hallo,

es wäre eine super Sache, wenn es auch eine Version geben würde, die man sich selbst beschriften kann. Freitext sozusagen.

Ja, es gibt schon welche, aber optisch sind diese hier nicht zu toppen.

Viele Grüße

Marc

**Comment by Achimobil** [comment]
Ich denke nicht das eine Frei Beschriftbare Version einfach so machbar ist und ich weiß auch nicht ob ich für den LS22 so was noch machen will, aber ich setze es mal auf die Wunschtliste

**Comment by Kitekater** [comment]
Dann kannst Du es ja schon für den LS 25 bauen. :-P
So wie das klingt, hast Du ja anscheinend schon Informationen :-D

**Comment by Achimobil** [comment]
Nee, aber ich hab so einiges hier liegen wo ich sage, dass ich es nicht mehr für den LS22 mache, wenn es einen LS25 gibt. Gibt es erst einen LS26 wird das wiederum interessant zu machen noch für den LS22. 
Meine eigene Karte z.B. Für den LS22 lohnt sich das anfangen nur, wenn es keinen LS25 gibt.
Ich hoffe auf der FarmCon endlich was zu erfahren

**Comment by Achimobil** [comment]
Im 22er gibt es keine Features mehr. Deshalb close ich das hier
