### ISSUE TITLE
Italian translation

### ISSUE THREAD

**Issue by Rudolfet** [Achimobil/FS22_BigDisplay#26]
We can add an Italian translation or is too late to do?

Thanks a lot.

PR #27

**Comment by Achimobil** [comment]
Yes, just send me or make a pull request and I will publish a new version with it.

**Comment by Rudolfet** [comment]
Do the PR. :-) Thanks for you :-)

**Comment by Achimobil** [comment]
Corrected and create a downloadable version with IT
This is not enough for creating an update in the ModHub, but will be there when an update is needed
https://github.com/Achimobil/FS22_BigDisplay/releases/tag/1.1.0.1
